 SELECT patients.id AS p_id,
    patients.age AS p_age,
    patients.gender AS p_gender,
    blood_pressures.id,
    blood_pressures.systolic,
    blood_pressures.diastolic,
    blood_pressures.patient_id,
    blood_pressures.created_at,
    blood_pressures.updated_at,
    blood_pressures.device_created_at,
    blood_pressures.device_updated_at,
    blood_pressures.facility_id,
    blood_pressures.user_id,
    blood_pressures.deleted_at,
    facilities.name,
    facilities.district,
    facilities.state,
    facilities.facility_type,
    users.full_name,
    users.sync_approval_status
   FROM patients,
    blood_pressures,
    facilities,
    users
  WHERE blood_pressures.patient_id = patients.id AND blood_pressures.facility_id = facilities.id AND blood_pressures.user_id = users.id;
