class GetBsnlTemplateDetails
  include I18n::Backend::Flatten
  include Memery

  attr_reader :template_details, :template_names

  def initialize
    @template_details = Messaging::Bsnl::Api.new.get_template_details
    @template_names = @template_details.map { |detail| detail["Template_Name"] }
  end

  def call
    validate_templates
    print_summary
    write_config_to_tmp_file
  end

  def pending_templates
    print_summary(list_pending: true)
    validate_templates
  end

  def validate_templates
    validate_names
    validate_statuses
  end

  def write_config_to_tmp_file
    config_file = "config/data/bsnl_templates.yml"
    config = template_details.to_h do |template|
      [
        template["Template_Name"],
        template.slice(
          "Template_Id", "Template_Keys",
          "Non_Variable_Text_Length", "Max_Length_Permitted",
          "Template_Status", "Is_Unicode"
        )
      ]
    end

    info "Added latest templates list to #{config_file}."
    info "Changes to this file (if any) should be committed to simple-server."

    File.open(config_file, "w") do |file|
      file.write("# This is an autogenerated file. Do not modify.\n")
      file.write("# Use get_bsnl_templates.rake to fetch a new copy of this file.\n")
      file.write(config.to_yaml)
    end
  end

  def print_summary(list_pending: false)
    uploaded_templates = []
    remaining_templates = []

    summary = locale_keys_by_language.map do |language, locale_keys|
      uploaded_for_language = 0
      locale_keys.each do |locale_key|
        if template_names.include?(locale_key)
          uploaded_templates << locale_key
          uploaded_for_language += 1
        else
          remaining_templates << locale_key
        end
      end

      {language: language,
       uploaded_count: uploaded_for_language,
       total_count: locale_keys.count}
    end

    info "✔ Found #{uploaded_templates.count}/#{locale_keys_by_language.values.flatten.count} templates on BSNL:"
    puts_list(summary.sort_by { |item| item[:uploaded_count] }.reverse.map do |item|
      "#{item[:uploaded_count]}/#{item[:total_count]} uploaded from #{item[:language]}"
    end)

    if list_pending
      info "✔ These messages have been uploaded to BSNL:"
      puts_list uploaded_templates.sort

      error "˟ These messages have not been uploaded to BSNL:"
      puts_list remaining_templates.sort
    end
  end

  def locale_keys_by_language
    Dir.glob("config/locales/notifications/*").to_h do |file_name|
      [file_name, flatten_translations(nil, YAML.safe_load(File.open(file_name)), nil, false).keys.map(&:to_s)]
    end
  end

  private

  def error(message)
    puts message.red
  end

  def warning(message)
    puts message.yellow
  end

  def info(message)
    puts message.green
  end

  def puts_list(array)
    puts array.to_yaml.delete_prefix("---\n")
  end

  def validate_names
    invalid_names = template_names.reject { |name| locale_keys_by_language.values.flatten.include?(name) }

    if invalid_names.any?
      error "⚠️  These templates are not in the notifications locale files but have been uploaded on DLT:"
      puts_list invalid_names
    end
  end

  def validate_statuses
    templates_pending_naming = template_details.select { |details| details["Template_Status"] == "0" }

    if templates_pending_naming.any?
      error "⚠️  These templates need to be named on the BSNL dashboard:"
      puts_list templates_pending_naming.map { |detail| detail["Template_Name"] }
    end
  end
end
