Config.ensure_required_keys_are_present(required_keys: [
  "DEFAULT_NUMBER_OF_RECORDS",
  "DEFAULT_COUNTRY",
  "SIMPLE_APP_SIGNATURE",
  "NEW_RELIC_LICENSE_KEY",
  "NEW_RELIC_APP_NAME",
  "SENDGRID_USERNAME",
  "SENDGRID_PASSWORD",
  "SENTRY_DSN",
  "SENTRY_CURRENT_ENV",
  "TWILIO_ACCOUNT_SID",
  "TWILIO_AUTH_TOKEN",
  "TWILIO_PHONE_NUMBER",
  "USER_OTP_VALID_UNTIL_DELTA_IN_MINUTES",
  "ENABLE_PURGE_ENDPOINT_FOR_QA",
  "EMAIL_SUBJECT_PREFIX",
  "SIMPLE_SERVER_ENV",
  "SIMPLE_SERVER_HOST",
  "SIMPLE_SERVER_HOST_PROTOCOL",
  "CALL_SESSION_REDIS_POOL_SIZE",
  "CALL_SESSION_REDIS_TIMEOUT_SEC",
  "HELP_SCREEN_YOUTUBE_VIDEO_URL",
  "HELP_SCREEN_YOUTUBE_PASSPORT_URL",
  "RAILS_CACHE_REDIS_PASSWORD",
  "SIDEKIQ_CONCURRENCY",
  "ANALYTICS_DASHBOARD_CACHE_TTL"
])

Config.ensure_required_keys_have_fallbacks(required_keys: {
  "CALL_SESSION_REDIS_HOST" => "REDIS_URL",
  "SIDEKIQ_REDIS_HOST" => "REDIS_URL",
  "RAILS_CACHE_REDIS_URL" => "REDIS_URL"
})
