require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dr_rai/actions", type: :request do
  # DrRai::Action. As you add validations to DrRai::Action, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DrRai::Action.create! valid_attributes
      get dr_rai_actions_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DrRai::Action" do
        expect {
          post dr_rai_actions_url, params: {dr_rai_action: valid_attributes}
        }.to change(DrRai::Action, :count).by(1)
      end

      it "redirects to the created dr_rai_action" do
        post dr_rai_actions_url, params: {dr_rai_action: valid_attributes}
        expect(response).to redirect_to(dr_rai_action_url(@dr_rai_action))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DrRai::Action" do
        expect {
          post dr_rai_actions_url, params: {dr_rai_action: invalid_attributes}
        }.to change(DrRai::Action, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dr_rai_actions_url, params: {dr_rai_action: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dr_rai_action" do
        action = DrRai::Action.create! valid_attributes
        patch dr_rai_action_url(dr_rai_action), params: {dr_rai_action: new_attributes}
        action.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dr_rai_action" do
        action = DrRai::Action.create! valid_attributes
        patch dr_rai_action_url(dr_rai_action), params: {dr_rai_action: new_attributes}
        action.reload
        expect(response).to redirect_to(dr_rai_action_url(action))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        action = DrRai::Action.create! valid_attributes
        patch dr_rai_action_url(dr_rai_action), params: {dr_rai_action: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dr_rai_action" do
      action = DrRai::Action.create! valid_attributes
      expect {
        delete dr_rai_action_url(dr_rai_action)
      }.to change(DrRai::Action, :count).by(-1)
    end

    it "redirects to the dr_rai_actions list" do
      action = DrRai::Action.create! valid_attributes
      delete dr_rai_action_url(dr_rai_action)
      expect(response).to redirect_to(dr_rai_actions_url)
    end
  end
end
