module ExternalLinksHelper
  INDIA_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/93706353132?pwd=U1EzczNuVm1FakppaGVNMWhaelFaQT09"
  BANGLADESH_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/94473705913?pwd=NWROVVoyTHFRcXJRaGVlU1k3bElFQT09"
  ETHIOPIA_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/93245696030?pwd=eGFmZnA5THd2Nmdhazl1TTRGYTFqdz09"

  DEPLOYMENT_CHECKLIST_LINK = "https://docs.google.com/document/d/1cleJkm09VRGUAafkpzC9U2ao9r4r8ewZjLPwfTTj57Q/edit?usp=sharing"

  INDIA_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1YKlZfXpnX0tGk6NMO6JLuZY0l9O3P3zOxKXsWNJh7W0/edit#slide=id.g25f6af9dd6_0_0"
  BANGLADESH_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1Ce2LIPlnByn-6LPhgbKUkhoGold3R5ciXtFbVXFOhaU/edit#slide=id.g25f6af9dd6_0_0"
  ETHIOPIA_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1GM57_sHZ53huaMCi1Vsg5O2aAjtXKWdLGvsvKzMROME/edit#slide=id.g25f6af9dd6_0_0"

  TRAINING_VIDEO_ALL_CHAPTERS_YOUTUBE_LINK = "https://youtu.be/MC_45DoRw2g"
  TRAINING_VIDEO_ALL_CHAPTERS_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XbQ9vejHXL8dXA0tuAyMvb0e9ToJR0yh/view?usp=sharing"
  HOW_TO_CONDUCT_A_TRAINING_YOUTUBE_LINK = "https://youtu.be/wfrMbvTXn38"
  HOW_TO_CONDUCT_A_TRAINING_DOWNLOAD_LINK = "https://drive.google.com/file/d/1X2jD3hMQwRNtmP51Ea0-JKxDqvdteeKe/view?usp=sharing"
  INSTALL_THE_APP_YOUTUBE_LINK = "https://youtu.be/r0mbu1s0l7A"
  INSTALL_THE_APP_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XDS-TkSAmxWFiAyTZ-XrGN7LIClGfz_M/view?usp=sharing"
  INTRODUCTION_YOUTUBE_LINK = "https://youtu.be/YPySS9sL-EU"
  INTRODUCTION_DOWNLOAD_LINK = "https://drive.google.com/file/d/1X4eKkSCLW0pQCseGKS5dfpaDhsTtO2ki/view?usp=sharing"
  REGISTER_A_PATIENT_YOUTUBE_LINK = "https://youtu.be/5P5mGQVQFOU"
  REGISTER_A_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XK17vrqvIdnOzVIF3r8lJIY7NODCQ8Ol/view?usp=sharing"
  SEARCH_FOR_PATIENT_YOUTUBE_LINK = "https://youtu.be/6hR1vQ8hoTU"
  SEARCH_FOR_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XMfLvj8ev5VXJIRFTU-Yrkg7iZNlgHRG/view?usp=sharing"
  FIND_PATIENT_YOUTUBE_LINK = "https://youtu.be/o3klwHrMEi0"
  FIND_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XLyY_lAEdnxcYJIyCHRg1VqhTfQ_uGpp/view?usp=sharing"
  CALL_OVERDUE_PATIENTS_YOUTUBE_LINK = "https://youtu.be/PuM29XINOn4"
  CALL_OVERDUE_PATIENTS_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XORZPiZuc0UbOEge9kGE-Eqd0LUjfKkP/view?usp=sharing"
  IMPORTANT_FEATURES_YOUTUBE_LINK = "https://youtu.be/elCBnApJLIM"
  IMPORTANT_FEATURES_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XS3nozUd1ip81_s2k9VYVnQPHb3eHa5d/view?usp=sharing"
  FAQ_YOUTUBE_LINK = "https://youtu.be/Aj-dKn_kmlw"
  FAQ_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XVTpv3taQQhUeFBctKKMVgkThxC4iF7O/view?usp=sharing"
  HOW_TO_GET_HELP_YOUTUBE_LINK = "https://youtu.be/wF4t_pFuugY"
  HOW_TO_GET_HELP_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XSZjssc20gfh8eO5l7BGNn-U6INS16qG/view?usp=sharing"
  START_USING_SIMPLE_YOUTUBE_LINK = "https://youtu.be/kls4QnWz1Nw"
  START_USING_SIMPLE_DOWNLOAD_LINK = "https://drive.google.com/file/d/1XZw2ZHMERapNhnnKcc8ENlwA1G492O88/view?usp=sharing"
  TELEMEDICINE_TRAINING_ENGLISH_YOUTUBE_LINK = "https://youtu.be/aI1bGpS08oY"
  TELEMEDICINE_TRAINING_HINDI_YOUTUBE_LINK = "https://youtu.be/JVfeNmY_n08"
  TELEMEDICINE_TRAINING_ENGLISH_DOWNLOAD_LINK = "https://drive.google.com/file/d/1ZWy-Umqc71ZSiUZlZ78QwrytSltXgxGk/view?usp=sharing"
  TELEMEDICINE_TRAINING_HINDI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1ZZCyKGvvNnUtjV4rS4Pe_Ujf8GZTye4P/view?usp=sharing"
  QUICK_SIMPLE_TRAINING_ENGLISH_YOUTUBE_LINK = "https://youtu.be/YjfPCUtZHlI"
  QUICK_SIMPLE_TRAINING_HINDI_YOUTUBE_LINK = "https://youtu.be/zthrk6XfpjQ"
  HOW_TO_USE_BP_PASSPORT_HINDI_YOUTUBE_LINK = "https://youtu.be/aktZ1yTdDOA"
  SIMPLE_DOCUMENTARY_SHORT_YOUTUBE_LINK = "https://youtu.be/C26CoyeExmU"
  SIMPLE_DOCUMENTARY_LONG_YOUTUBE_LINK = "https://youtu.be/G0Pj_2aFGCQ"

  ONE_PAGER_INDIA_LINK = "https://drive.google.com/a/resolvetosavelives.org/file/d/1M2BpHYZALN8UAOaLZUfwFKCRvmq0fI7s/view?usp=sharing"
  ONE_PAGER_SIMPLE_LINK = "https://drive.google.com/open?id=1LzGcSK5nPS0izJT4kV7B3y6syl84ACqo&authuser=dburka%40resolvetosavelives.org&usp=drive_fs"

  APP_USERS_GUIDE_AMHARIC_DOWNLOAD_LINK = "https://drive.google.com/file/d/1_RemdV7sOgTPsihXOxRp9Ud_ZV8DP1U_/view?usp=sharing"
  APP_USERS_GUIDE_BENGALI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1yHBxU1gifqqDbwhkc1vgd-fg6NxKTj9i/view?usp=sharing"
  APP_USERS_GUIDE_ENGLISH_DOWNLOAD_LINK = "https://drive.google.com/file/d/1mFE2sFtDkUqCxGS-jBfUfrVHvqqtNHoU/view?usp=sharing"
  APP_USERS_GUIDE_HINDI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1fVFZZZu9sW8jxsM2H11d7jmbjV8RJzA_/view?usp=sharing"
  APP_USERS_GUIDE_MARATHI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1v_B9uoI4zmKDXJFQ0bigjB6-ChuMUngh/view?usp=sharing"
  APP_USERS_GUIDE_OROMO_DOWNLOAD_LINK = "https://drive.google.com/file/d/1ho_g1tOkY6r8oWItKLRqkaQITUuyWEOq/view?usp=sharing"
  APP_USERS_GUIDE_PUNJABI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1NkcvXFXjnabhO8aVRZkvcbgf3kaEJugO/view?usp=sharing"
  APP_USERS_GUIDE_TAMIL_DOWNLOAD_LINK = "https://drive.google.com/file/d/18SquYM3RrtZSAbyocnOnPDtzLMtEctRp/view?usp=sharing"
  APP_USERS_GUIDE_TELUGU_DOWNLOAD_LINK = "https://drive.google.com/file/d/1otvYVtmHu0QXTpdcst8EgIlwU5Tkqv5V/view?usp=sharing"
  APP_USERS_GUIDE_TIGRINYA_DOWNLOAD_LINK = "https://drive.google.com/file/d/11vosmjIiLKDoMlOyd5vHICPBOKX1k2lE/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_AMHARIC_DOWNLOAD_LINK = "https://drive.google.com/file/d/1EuQ8VanfY2qFBu22-HhK6Duaue0GyifN/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_BENGALI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1_k8IhV6NsMClwZTi_vzkeZgEeK_09cq-/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_ENGLISH_DOWNLOAD_LINK = "https://drive.google.com/file/d/1DK90sSCIn1y-MvAAYktbFyYhqxreKHea/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_HINDI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1qnh9GEfEl1zMz10-yzKeT39bFIMRO2VV/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_MARATHI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1Qd8EIxyeL3A4Ok1xjllzw0TaVIgleeW1/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_OROMO_DOWNLOAD_LINK = "https://drive.google.com/file/d/1EWE4bdlqN8aLrzAysP-jUGdEUXv8Hakd/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_PUNJABI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1MgGKXdwslTSA2xlKMwMa8M6-o486NMLs/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_TAMIL_DOWNLOAD_LINK = "https://drive.google.com/file/d/1sb2xnwKGjVZCSTSktVtATot0e2ZF9lj6/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_TELUGU_DOWNLOAD_LINK = "https://drive.google.com/file/d/1FvgNytO9WYLl3QkJD5hObOCJLwq4BeHw/view?usp=sharing"
  HOW_TO_TAKE_A_BP_POSTER_TIGRINYA_DOWNLOAD_LINK = "https://drive.google.com/file/d/16yQIyykh1EBNxmzTKfD6Ett__NrSvL0y/view?usp=sharing"
end
