module ExternalLinksHelper
  INDIA_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/93706353132?pwd=U1EzczNuVm1FakppaGVNMWhaelFaQT09"
  BANGLADESH_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/94473705913?pwd=NWROVVoyTHFRcXJRaGVlU1k3bElFQT09"
  ETHIOPIA_OFFICE_HOURS_ZOOM_LINK = "https://vitalstrategies.zoom.us/j/93245696030?pwd=eGFmZnA5THd2Nmdhazl1TTRGYTFqdz09"

  DEPLOYMENT_CHECKLIST_LINK = "https://docs.google.com/document/d/1cleJkm09VRGUAafkpzC9U2ao9r4r8ewZjLPwfTTj57Q/edit?usp=sharing"

  INDIA_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1YKlZfXpnX0tGk6NMO6JLuZY0l9O3P3zOxKXsWNJh7W0/edit#slide=id.g25f6af9dd6_0_0"
  BANGLADESH_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1Ce2LIPlnByn-6LPhgbKUkhoGold3R5ciXtFbVXFOhaU/edit#slide=id.g25f6af9dd6_0_0"
  ETHIOPIA_SIMPLE_TRAINING_GUIDE_LINK = "https://docs.google.com/presentation/d/1GM57_sHZ53huaMCi1Vsg5O2aAjtXKWdLGvsvKzMROME/edit#slide=id.g25f6af9dd6_0_0"

  TRAINING_VIDEO_ALL_CHAPTERS_YOUTUBE_LINK = "https://youtu.be/MC_45DoRw2g"
  TRAINING_VIDEO_ALL_CHAPTERS_DOWNLOAD_LINK = "https://drive.google.com/file/d/1-uumJE8w-BaDroppG3P0K-BK4LAGN3f0/view?usp=sharing"
  HOW_TO_CONDUCT_A_TRAINING_YOUTUBE_LINK = "https://youtu.be/wfrMbvTXn38"
  HOW_TO_CONDUCT_A_TRAINING_DOWNLOAD_LINK = "https://drive.google.com/file/d/1grHi-XhWZFUkP5Wfke88FB_vlzO3uHpo/view?usp=sharing"
  INSTALL_THE_APP_YOUTUBE_LINK = "https://youtu.be/r0mbu1s0l7A"
  INSTALL_THE_APP_DOWNLOAD_LINK = "https://drive.google.com/file/d/15IqT-GnLAkqP_qx-41607bSgaXdqMefs/view?usp=sharing"
  INTRODUCTION_YOUTUBE_LINK = "https://youtu.be/YPySS9sL-EU"
  INTRODUCTION_DOWNLOAD_LINK = "https://drive.google.com/file/d/18reVHNwMlqbRt6wA8yaCo4Gsxz_3CLA3/view?usp=sharing"
  REGISTER_A_PATIENT_YOUTUBE_LINK = "https://youtu.be/5P5mGQVQFOU"
  REGISTER_A_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1QfiQ0gzUeKkEpIamc3VZPYmDcta-emmO/view?usp=sharing"
  SEARCH_FOR_PATIENT_YOUTUBE_LINK = "https://youtu.be/6hR1vQ8hoTU"
  SEARCH_FOR_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1q0ac-Rz8UvNpzgGnAhGlWekmK53YXHQg/view?usp=sharing"
  FIND_PATIENT_YOUTUBE_LINK = "https://youtu.be/o3klwHrMEi0"
  FIND_PATIENT_DOWNLOAD_LINK = "https://drive.google.com/file/d/1UBqI6AZThvnlBsL62_I26jOOaDyBy7ND/view?usp=sharing"
  CALL_OVERDUE_PATIENTS_YOUTUBE_LINK = "https://youtu.be/PuM29XINOn4"
  CALL_OVERDUE_PATIENTS_DOWNLOAD_LINK = "https://drive.google.com/file/d/1Sj9NGf0MC7loDhSScvs9jO26X91_Gu5a/view?usp=sharing"
  IMPORTANT_FEATURES_YOUTUBE_LINK = "https://youtu.be/elCBnApJLIM"
  IMPORTANT_FEATURES_DOWNLOAD_LINK = "https://drive.google.com/file/d/1p5mjZ8KWRlPdZRf1YypFcaSqhdLZacxe/view?usp=sharing"
  FAQ_YOUTUBE_LINK = "https://youtu.be/Aj-dKn_kmlw"
  FAQ_DOWNLOAD_LINK = "https://drive.google.com/file/d/1rFjIdquF3zpMiskHWB50q810ABEq0gwk/view?usp=sharing"
  HOW_TO_GET_HELP_YOUTUBE_LINK = "https://youtu.be/wF4t_pFuugY"
  HOW_TO_GET_HELP_DOWNLOAD_LINK = "https://drive.google.com/file/d/1FTsVx_ng5a-C1s_kS4nFYX5Y-dgHsL0r/view?usp=sharing"
  START_USING_SIMPLE_YOUTUBE_LINK = "https://youtu.be/kls4QnWz1Nw"
  START_USING_SIMPLE_DOWNLOAD_LINK = "https://drive.google.com/file/d/1SKXNRMfOQ5P2VPOWvDSLS-djvbqT5q3t/view?usp=sharing"
  TELEMEDICINE_TRAINING_ENGLISH_YOUTUBE_LINK = "https://youtu.be/LpLeFFKhXd4"
  TELEMEDICINE_TRAINING_HINDI_YOUTUBE_LINK = "https://youtu.be/lMS1GiqbKps"
  TELEMEDICINE_TRAINING_ENGLISH_DOWNLOAD_LINK = "https://drive.google.com/file/d/1YRPvaIeqkI8pellzvY8kBz6K2FLgxTdu/view?usp=sharing"
  TELEMEDICINE_TRAINING_HINDI_DOWNLOAD_LINK = "https://drive.google.com/file/d/1fiQ-kLWqcO8_SCcac7gjA9kMjxM4lFHs/view?usp=sharing"
  QUICK_SIMPLE_TRAINING_ENGLISH_YOUTUBE_LINK = "https://youtu.be/YjfPCUtZHlI"
  QUICK_SIMPLE_TRAINING_HINDI_YOUTUBE_LINK = "https://youtu.be/zthrk6XfpjQ"
  HOW_TO_USE_BP_PASSPORT_HINDI_YOUTUBE_LINK = "https://youtu.be/aktZ1yTdDOA"
  SIMPLE_DOCUMENTARY_SHORT_YOUTUBE_LINK = "https://youtu.be/C26CoyeExmU"
  SIMPLE_DOCUMENTARY_LONG_YOUTUBE_LINK = "https://youtu.be/G0Pj_2aFGCQ"

  ONE_PAGER_INDIA_LINK = "https://drive.google.com/a/resolvetosavelives.org/file/d/1M2BpHYZALN8UAOaLZUfwFKCRvmq0fI7s/view?usp=sharing"
  ONE_PAGER_SIMPLE_LINK = "https://drive.google.com/open?id=1LzGcSK5nPS0izJT4kV7B3y6syl84ACqo&authuser=dburka%40resolvetosavelives.org&usp=drive_fs"

  APP_USERS_GUIDE_LINK = "https://drive.google.com/file/d/1MM2dEpUBgE3EyZS9CrzuxgjHqIQa3eb1/view"
  HOW_TO_TAKE_A_BP_POSTER_LINK = "https://drive.google.com/file/d/1lhiYrXAWqL_QVRurm6gs7Gdh0t3Wm-Wv/view?usp=sharing"
end
