#!/bin/bash
# Simple time based benchmark - credit to https://gist.github.com/peterjmit/3864743 that this is modified from
#
# Note: this requires the GNU version of time installed. On mac you can `brew install gnu-time` to install it.
#
# Examples
#   bench -c "bin/rails db:reset"
#   bench -c "bin/rspec"
#   bench -c "whatever_script_you_want"
set -e

repeats=3
output_file='benchmark_results.csv'
command_to_run='echo 1'

run_tests() {
  # --------------------------------------------------------------------------
  # Benchmark loop
  # --------------------------------------------------------------------------
  echo
  echo 'Benchmarking '$command_to_run '...'

  # Indicate the command we just run in the csv file
  echo '==' $command_to_run '======' >> $output_file;

  # Run the given command [repeats] times
  for (( i = 1; i <= $repeats ; i++ ))
  do
      # percentage completion
      p=$(( $i * 100 / $repeats))
      # indicator of progress
      l=$(seq -s "+" $i | sed 's/[0-9]//g')

      # runs time function for the called script, output in a comma seperated
      # format output file specified with -o command and -a specifies appendo
      # output format is real (wall clock) time, user time, and system time
      gtime -f "%C,%E,%U,%S" -o ${output_file} -a ${command_to_run} > /dev/null

      # Clear the HDD cache (I hope?)
      # sync && echo 3 > /proc/sys/vm/drop_caches

      echo -ne ${l}' ('${p}'%) \r'
  done;
  echo "== Done ======" >> $output_file;
  echo >> $output_file
}

# Option parsing
while getopts n:c:o: OPT
do
  case "$OPT" in
    n)
      repeats=$OPTARG
      ;;
    o)
      output_file=$OPTARG
      ;;
    c)
      command_to_run=$OPTARG
      run_tests
      ;;
    \?)
      echo 'No arguments supplied'
      exit 1
      ;;
  esac
done

shift `expr $OPTIND - 1`