#!/usr/bin/env ruby
#
# Harness for runnign datascripts

script = ARGV[0] || raise(ArgumentError, "You must provide the name a script, for example: script/run_data_script update_user_emails")
write_mode = ARGV[1] || false

require_relative "../config/environment"
require_relative "../lib/data_scripts/#{script}"

klass = script.classify.constantize
klass.call(dry_run: !write_mode)

puts
puts "Done!"
