#!/bin/sh
set -ex

sem-service start postgres 10
sem-version ruby 2.6.6
wget -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
sudo dpkg -i /tmp/libpng12.deb
gem install semaphore_test_boosters
cache restore
yarn install
bundle install --deployment --path vendor/bundle
cache store