#!/bin/bash -v
set -e

# See https://github.com/semaphoreci/toolbox for more details on the "sem-" commands
source ~/.toolbox/toolbox

# Temporarily turn on cache clear if Semaphore has weird bundling issues
cache clear

export DD_PROFILING_NO_EXTENSION=true
sem-version ruby 2.7.4
sem-service start postgres 14
sem-service start redis 5

# wkhtmltoimage-binary gem dependencies
sudo add-apt-repository ppa:linuxuprising/libpng12 -y
sudo apt update
sudo apt install libpng12-0 -y
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.1f-1ubuntu2_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.1f-1ubuntu2_amd64.deb

gem install semaphore_test_boosters
# cache restore
yarn install
bundle config set deployment 'true'
bundle config set path 'vendor/bundle'
bundle install
bundle exec rake db:setup
bundle exec rake db:test:prepare
RAILS_ENV="test" bundle exec rails db:refresh_matviews
# cache store
