#!/bin/bash
set -ex

# See https://github.com/semaphoreci/toolbox for more details on the "sem-" commands
source ~/.toolbox/toolbox

# Temporarily turn on cache clear if Semaphore has weird bundling issues
# cache clear

sem-version ruby 2.7.4
sem-service start postgres 10
wget -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
sudo dpkg -i /tmp/libpng12.deb
gem install semaphore_test_boosters
cache restore
yarn install
bundle config set deployment 'true'
bundle config set path 'vendor/bundle'
bundle install
bundle exec rake db:setup
bundle exec rake db:test:prepare
RAILS_ENV="test" bundle exec rails db:refresh_matviews
cache store