version: v1.0
name: Sri Lanka Production Deployment AWS
blocks:
  - name: Deploy to Sri Lanka Production AWS
    task:
      secrets:
        - name: sentry-release-auth-token
        - name: semaphore-deploy-key
      jobs:
        - name: Deploy to Sri Lanka Production AWS
          commands:
            - checkout
            - deploy_target=sri-lanka:production script/semaphore_deploy
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
