name: Android QA tests

on: pull_request

jobs:
  android_qa_tests:
    runs-on: [ macos-latest ]
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout simple-android
        uses: actions/checkout@v2
        with:
          repository: simpledotorg/simple-android
          path: simple-android

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: QA Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: simple-android/gradlew -p simple-android -PmanifestEndpoint="https://simple-review-pr-$PR_NUMBER.herokuapp.com/api/" connectedQaDebugAndroidTest
