name: Build & push Docker image

on:
  push:
    branches: [ containerization, master ]

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: simpledotorg/server
          tags: $GITHUB_SHA, latest
          registry: docker.io
          dockerfile: Prod-passenger.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy_simple_server_qa:
    needs: docker_build_push
    runs-on: ubuntu-latest
    container:
      image: argoproj/argocd:v2.4.11
      options: --user 0
    steps:
      - uses: actions/checkout@v2
      - name: Argocd deployment
        run: ${GITHUB_WORKSPACE}/script/argocd_deployment.sh ${{ secrets.QA_ARGOCD_ENDPOINT }} ${{ secrets.ARGOCD_USERNAME }} ${{ secrets.QA_ARGOCD_PASSWORD }}
